### ISSUE TITLE
Warning notice 

### ISSUE THREAD

**Issue by Alvin201777** [DW8030/Policy-mod#4]
![Screenshot_2023-07-06-05-04-28-117_com unciv app](https://github.com/EmperorPinguin/Policy-mod/assets/132994815/bab1d1b4-2fa9-4946-a257-59177000bf5c)
![IMG-20230706-WA0000](https://github.com/EmperorPinguin/Policy-mod/assets/132994815/3d990182-7b68-4b0f-b4b8-c99fb84b9cee)

Bro, policy mod There are bugs, there are warnings and when you force play, a force close will occur when choosing a culture of reform. See screenshot 2

**Comment by Alvin201777** [comment]
Go to #9749

**Comment by EmperorPinguin** [comment]
Thank you for reporting the error! I copied the uniques from RekMOD, assuming they'd work - they didn't.



What mod are you using for your "Food Supply" policy tree, if I may ask?

**Comment by Alvin201777** [comment]
> Thank you for reporting the error! I copied the uniques from RekMOD, assuming they'd work - they didn't.
> 
> What mod are you using for your "Food Supply" policy tree, if I may ask?

Food supply is another Mod, i use it for city in snow tile
